export default {
  logo: require('../assets/Images/icLogoOrange.png'),
  facebook_Icon: require('../assets/Images/icFb.png'),
  instagram_Icon: require('../assets/Images/icInstagram.png'),
  back_arrow: require('../assets/Images/leftArrow.png'),
  show_password: require('../assets/Images/icEyeActive.png'),
  hide_password: require('../assets/Images/icEyeInactive.png'),
  home_selected: require('../assets/Images/icHomeSelected.png'),
  home_unselected: require('../assets/Images/icHomeUnselected.png'),
  search_selected: require('../assets/Images/icSearchSelected.png'),
  search_unselected: require('../assets/Images/icSearchUnselected.png'),
  profile_selected: require('../assets/Images/icProfileSelected.png'),
  profile_unselected: require('../assets/Images/icProfileUnselected.png'),
  notification_selected: require('../assets/Images/icNotificationSelected.png'),
  notification_unselected: require('../assets/Images/icNotificationUnselected.png'),
  setting_selected: require('../assets/Images/icSettingsSelected.png'),
  setting_unselected: require('../assets/Images/icSettingsUnselected.png'),
  vote_button: require('../assets/Images/icPlusSign.png'),
  current_challange: require('../assets/Images/currentChallanges.jpeg'),
  currentChallange_Icon: require('../assets/Images/icDollar.png'),
  upcoming_challange: require('../assets/Images/challengeAccepted.jpeg'),
  upcoming_icon: require('../assets/Images/icCalendar.png'),
  hall_of_fame: require('../assets/Images/trophy.jpeg'),
  fame_icon: require('../assets/Images/icTrophy.png'),
};
